name: Recover Secret
on: push
jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Print encoded secret
        env:
          SECRET_DATA: ${{ secrets.PHANTOM_PINTEREST_CODE }}
        run: |
          echo "$SECRET_DATA" | base64
